#%RAML 1.0 Library
traits:
  transactionId:  !include traits/headers-transactionId-trait.raml
  departureLocationCode: !include traits/queryparams-departureLocationCode-trait.raml
  destinationLocationCode: !include traits/queryparams-destinationLocationCode-trait.raml
types:
  commonError: !include /libraries/common/dataTypes/commonerror-dataType.raml