#%RAML 1.0
title: RetrieveConsolidatedRoutesandSchedule-FastGo-SAPI
description: This Raml will fetch Route and Schedule from FastGo Transport Provider 
uses:
  common: libraries/common/common-Business-library.raml
  routes: /libraries/routes/routes-business-library.raml
  Schedules: /libraries/schedules/getSchedules-business-library.raml
/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        is:
          - common.transactionId
        responses:
          200:
            body:
              application/json:
                type: routes.getRoutes
                example:  !include libraries/routes/examples/getroutes-200response-example.json
          400:
            body:
              application/json:
                type: common.commonError
                example:  !include libraries/common/examples/400response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example: !include libraries/common/examples/404response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example:  !include libraries/common/examples/500response-example.json                                     
    /schedules: 
      get:
        is:
          - common.transactionId
          - common.departureLocationCode
          - common.destinationLocationCode
        responses:
          200:
            body:
              application/json:
                type: Schedules.getSchedules
                example:  !include libraries/schedules/examples/getSchesules-200response-example.json
          400:
            body:
              application/json:
                type: common.commonError
                example:  !include libraries/common/examples/400response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example:  !include libraries/common/examples/404response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example:  !include libraries/common/examples/500response-example.json                           